name = "GregTech CEu Modern Community Pack Sparkinex Edition"
author = "ursamina"
version = "1.14.5-sparx1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2340256596152ccd2b7e5526ff25144bbfc5ffc1a19c30558e560a7d630772ef"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
